### ISSUE TITLE
Error parsing commandline arguments: unknown short flag '-c'

### ISSUE THREAD

**Issue by AATHITH** [RobustPerception/prometheus_examples#2]
I have created deployment with
`kubectl create -f https://github.com/RobustPerception/prometheus_examples/blob/master/kubernetes_examples/azure-k8s-prometheus-grafana/prometheus/prometheus-deployment.yml`

pod created successfully but getting the following error
> k logs prometheus-deployment-9795cc967-khkwh
> Error parsing commandline arguments: unknown short flag '-c'
> prometheus: error: unknown short flag '-c'

**Comment by brian-brazil** [comment]
Looks like that was written for Prometheus 1.x.x, I'd suggest looking at the Prometheus Operator.
